apiVersion: v1
kind: Service
metadata:
  name: alloy-logs
  namespace: observability
  labels:
    app.kubernetes.io/name: alloy-logs
    app.kubernetes.io/part-of: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: alloy-logs
  ports:
    - name: http
      port: 12345
      targetPort: http
