apiVersion: v1
kind: Service
metadata:
  name: pantry-private-api
  namespace: pantry-bot
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: pantry-private-api
    app.kubernetes.io/part-of: pantry-bot
spec:
  selector:
    app.kubernetes.io/name: pantry-private-api
  ports:
    - name: http
      port: 3000
      targetPort: http
  type: ClusterIP
